name: List Workspaces

on:
  workflow_call:
    inputs:
      tenant_name:
        required: false
        type: string
      tenant_environment:
        required: false
        type: string
      workspace_name:
        required: false
        type: string
      config_path:
        required: false
        type: string
    outputs:
      matrix_jobs:
        description: "Matrix jobs based on tenant workspaces"
        value: ${{ jobs.list-workspaces.outputs.matrix_jobs }}

jobs:
  list-workspaces:
    runs-on: ubuntu-latest
    outputs:
      matrix_jobs: ${{ steps.extract-workspaces.outputs.matrix_jobs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Extract workspaces
        id: extract-workspaces
        env:
          tenant_name: ${{ inputs.tenant_name }}
          tenant_environment: ${{ inputs.tenant_environment }}
          config_path: ${{ inputs.config_path }}
          workspace_name: ${{ inputs.workspace_name }}
        run: |
          python3 bootstrap/matrix-generator.py

